### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by eladcandroid** [ingram-projects/animxyz#10]
Maybe you can achieve it quickly with https://github.com/antfu/vue-demi

**Comment by redsuperbat** [comment]
I forked the monorepo to try implementing it. However since it is a monorepo it seems like it's not possible to have more than one version of Vue.

**Comment by eladcandroid** [comment]
@redsuperbat Vue-demi should let you to do it.. Please check my link

**Comment by milesingrams** [comment]
I love the idea of vue-demi! I plan to work on this as soon as possible and see if I can get something out. Due to the multiple breaking changes in Vue3 for transitions and functional components I was worried I'd have to make a new package specifically for Vue3 but this might be the solution. I'll get back to you all with updates.

**Comment by milesingrams** [comment]
Working hard on this! Pretty sure I've got Vue3 support completed but just got to do a few more tests and checks to make sure it works as expected. Expect something in the next few days. Happy holidays!

**Comment by milesingrams** [comment]
Vue3 support is live!!!

The Vue3 package is separate and is called `@animxyz/vue3` and should work identically to the Vue2 plugin (although plugin install is different due to changes in how Vue3 works).

Full installation instructions can be found here: https://animxyz.com/docs#vue-installation .

The vue-demi route worked very well in some situations but it would cause issues with environments which don't run dependency postinstall hooks like codesandbox so I decided to go with a separate package.

Let me know what you think!
