### ISSUE TITLE
nuxt support ?

### ISSUE THREAD

**Issue by flapili** [ingram-projects/animxyz#13]
Hi, does animxyz support nuxt ? I'm unable to use it

I tried with a plugin
```js
import Vue from 'vue'
import VueAnimXYZ from '@animxyz/vue'

Vue.use(VueAnimXYZ)
```
and import from CDN but there is no animations at all

```html
<template>
  <div>
    <input type="button" value="test" @click="show = !show" />
    <XyzTransition xyz="fade">
      <div class="square" v-if="show">test</div>
    </XyzTransition>
  </div>
</template>

<script>
export default {
  data() {
    return {
      show: true,
    };
  },
};
</script>

<style scoped>
.square {
  width: 100px;
  height: 100px;
  background-color: red;
}
</style>
```

and that is the rendered DOM
```html
<div data-v-2a183b29=""
    <input type="button" value="test" data-v-2a183b29="">
    <div data-v-2a183b29="" xyz="fade" class="square xyz-in-to">test</div>
</div>
```
as you can see the xyz property is correctly applied

**Comment by milesingrams** [comment]
That all looks correct! Since it's a CSS library you need to also include the CSS or SCSS somewhere in your code. did you do that?
Since I believe Nuxt uses CSS loader you can probably just add `import '@animxyz/core` underneath the VueAnimXYZ import.

**Comment by flapili** [comment]
you are totally right !
I had to add `import '@animxyz/core/dist/animxyz.min.css'`, `import '@animxyz/core'` result as "Invalid or unexpected token".
Should I make a upll request to clarify the doc ?

**Comment by milesingrams** [comment]
Glad it worked out! I definitely think we need to clarify in the Vue Installation section that the CSS needs to be included as well for it to work. I wonder if theres a way of having the CSS automatically import with the package while still allowing people to use jsdelivr. Gonna have to think about that since it would make it easier. Thanks for pointing out this issue!

**Comment by milesingrams** [comment]
I'm gonna investigate that 'unexpected token' error as well for not including the deep path.

**Comment by flapili** [comment]
> I wonder if theres a way of having the CSS automatically import with the package
the  CSS is really huge (around 100ko) so without a way to purge the inused CSS I don't think it's a good idea, or maybe provide an option to import the CSS.
An other idea is you could split the CSS in smaller parts to give more granular control, maybe split keyframes and `[xyz~=things]` rules

**Comment by mattaningram** [comment]
I think splitting the core and utility CSS or providing some config to do so is a good idea. We'll look into ways to do that. A way to purge unused utilities may also be possible in the future since the purger would only need to look at the `xyz` attribute (although wouldn't take into account dynamic `v-xyz`).

**Comment by ram-you** [comment]
I think we should use purgeCSS as suggested by Sebastien Chopin.
https://twitter.com/Atinux/status/1340262382120132609?s=20

**Comment by flapili** [comment]
I tried it yesterday but unfortunally purgeCSS removed too much CSS
![image](https://user-images.githubusercontent.com/29481952/102692986-9c5db500-4217-11eb-86c2-f07af3bcb118.png)

**Comment by eserdinyo** [comment]
I added css file to my plugin. And its working now.

```javascript
import Vue from 'vue'
import VueAnimXYZ from '@animxyz/vue'
import '@animxyz/core/dist/animxyz.min.css'

Vue.use(VueAnimXYZ)
```

**Comment by mattaningram** [comment]
Closing for now. Feel free to open a PR with clearer documentation @flapili. We should clarify the different ways to import styles (directly in JS or imported into CSS or SCSS).

**Comment by Tuginho** [comment]
Do we need to wrap it in <client-only> tag? 
Because nuxt is SSR and I dont know if its working with appear-visible.

**Comment by eserdinyo** [comment]
@Tuginho You can register the plugin with client-mode.
[Here is the doc.](https://nuxtjs.org/docs/directory-structure/plugins/#client-or-server-side-only)

**Comment by mattaningram** [comment]
@Tuginho @eserdinyo Yeah SSR causes some issues for `appear-visible` because the static HTML renders before the JS hydrates and knows what parts of the page should be kept hidden, so you sometimes see a flash of content before it is animated in. Likely an issue with SSR animations with any framework. You can fake it by hiding the static HTML by default and then it will look better, but if JS doesn't load or is turned off then the content will never become visible.
