### ISSUE TITLE
SassError

### ISSUE THREAD

**Issue by productfrontenddeveloper** [ingram-projects/animxyz#15]
```/node_modules/@angular-builders/custom-webpack/node_modules/sass-loader/dist/cjs.js):
SassError: $color: var(--xyz-in-filter-grayscale, var(--xyz-filter-grayscale, 100%)) is not a color.
      ╷
51647 │     filter: grayscale(var(--xyz-in-filter-grayscale, var(--xyz-filter-grayscale, 100%)));
      │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
``` 

i am import 

```// Import the functions/mixins
@import '@animxyz/core';

// Add all the core/utilities selectors
@include xyz-all;
// --- Or for more control and granularity ---
@include xyz-core;
@include xyz-utilities;
``` 

and angular will support come?

**Comment by milesingrams** [comment]
Oh interesting! I think this is due to a confusion between the sass "grayscale" function and the css filter function. I can fix this later today. As for Angular is is a similar situation as Svelte. We will make a plug-in for it but given that Angular doesn't have a class-based transition system or similar library available it will need to be custom and may take some time.

**Comment by milesingrams** [comment]
In the current stable release (v0.1.2) I have removed the offending code so hopefully this shouldn't be an issue. We have seen some other issues with scss imports related to our development being in the latest dart-sass implementation which apparently has some non backwards compatible features. We are working hard to iron those bugs out!
