### ISSUE TITLE
The animations on your website don't work. 

### ISSUE THREAD

**Issue by stratboy** [ingram-projects/animxyz#19]
They don't run both on ff and chrome.

**Comment by mattaningram** [comment]
I'm guessing this is due to you having "Prefers reduced motion" setting on your OS. We turn off animations when we detect that setting since it is considered a good practice for accessibility. We should clarify this in the documentation and have an alert stating animations won't run when it detects that setting.

You can see how to toggle the setting for your OS here: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion#User_preferences

Let me know if that doesn't fix it!

**Comment by milesingrams** [comment]
We are currently working on a visual cue to users of our documentation site that will indicate if they have the accessibility feature 'prefers-reduced-motion' activated. This should make it clear for those users why the animations are not visible.

**Comment by mattaningram** [comment]
Indicator for "prefers reduced motion" is now live. I'm going to close this issue unless that doesn't solve problem.

**Comment by ricky11** [comment]
anyway to override reduce motion (just for testing purposes) i could not find the media query wher eyou turn off animations.

**Comment by mattaningram** [comment]
@ricky11 You can temporarily turn reduced motion on and off in Chrome-based browsers dev tools in the Rendering panel. I imagine Safari and Firefox have something similar.

Otherwise the media query only appears on elements that have an animation class on them, so you can manually add an `xyz-in` to an element and inspect it and you will see CSS setting the animation to none.

![image](https://user-images.githubusercontent.com/955092/133654316-6404b6e3-085e-47bf-8614-b22b2ff249db.png)

**Comment by ricky11** [comment]
I found in Windows there was a option for windows animation.  didn't say anything about reduced motion.
that did the trick.
however i would like to see if i can turn this setting off for xyz?

can i transition a div height?
