### ISSUE TITLE
Importing library into Sass files throws error:

### ISSUE THREAD

**Issue by Sananes** [ingram-projects/animxyz#22]
I've been trying to import the `@import '@animxyz/core'` and for some reason get the following error:

```
ERROR in ./src/assets/style/index.scss (./node_modules/css-loader/dist/cjs.js??ref--4-oneOf-1-1!./node_modules/postcss-loader/src??ref--4-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/style-resources-loader/lib??ref--4-oneOf-1-4!./src/assets/style/index.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: no mixin named xyz-core
        on line 12 of node_modules/@animxyz/core/src/animxyz.scss, in mixin `xyz-all`
        from line 2 of src/assets/style/general/_animations.scss
        from line 1 of src/assets/style/general/index.scss
        from line 8 of C:\Users\san\Projects\untitled-project\web\src\assets\style\index.scss
>>   @include xyz-core;

   -----------^
  ```
  
  Not quite sure what the issue is.

Any help will be appreciated, thanks again!

**Comment by milesingrams** [comment]
No worries! Thanks for pointing out these issues. We need people like you to help us find the bugs since this is a brand-new library.

Currently I'm trying to figure out why this works in our repository but not on codesandbox and in your repository. I'm worried I may have used the *newest* sass syntax which might be breaking things (`@use` instead of `@import`). Gonna try some stuff out and let you know what I find.

**Comment by Nikolasgrizli** [comment]
Hi, milesingrams, you made a great library, thanks, but i have the same problem ((
![image](https://user-images.githubusercontent.com/12588128/109052272-1a40af80-76e4-11eb-8a5e-163d702aefcb.png)

**Comment by milesingrams** [comment]
Hi Nikolas! Thank you for the feedback.
For your first question regarding Sass I am unable to reproduce this issue but I will keep looking into it. 

However we are currently migrating to a postCSS based config instead of Sass which will allow for generating all utilities instead of precompiling. The benefit will be that you can use many more utilities with no impact to your bundle size. So for now, maybe instead of importing to Sass, try the standard CSS import by importing into your main javascript file?

In main JS file:
`
import '@animxyz/core'
`

And for your second question, the difficulty with hover is that it usually only works smoothly with the CSS `transition` property not `animation`. So i don't know if it would look good to do animation on hover. It will move smoothly when entering hover but will jump back when you leave hover.

Let me know if moving the import works! I'm sorry I couldn't give you a more in depth answer currently.

**Comment by televators** [comment]
Reporting in with same issues. After reading your replies above, I tried replacing the `@forward` statements in src/animxyz.scss with `@import` and I got past that specific issue.

However, now I am getting a new error:
```
Error in plugin "sass"
Message:
    node_modules/@animxyz/core/src/_variables.scss
Error: Invalid CSS after "...modes-all: list": expected expression (e.g. 1px, bold), was ".join('all', $xyz-m"
        on line 7 of node_modules/@animxyz/core/src/_variables.scss
        from line 1 of node_modules/@animxyz/core/src/animxyz.scss
        from line 2 of src/scss/main.scss
>> $xyz-modes-all: list.join('all', $xyz-modes);

   --------------------^
```
I haven't had a reason to read up on the different versions of Sass (and the various implementations like libsass, dartsass, node-sass, gulp-sass, etc) but I imagine whatever version of Sass being used under the hood in @Sananes and my cases is older than what Animxyz was built under.

I'm using gulp-sass^4.0.2 (4.1.0 currently) which uses node-sass^4.8.3 (4.14.1 currently). Running Node v10 through NVM on Ubuntu 20.04 via WSL2 on Windows 10 202H. Pulled latest version of animxyz from NPM so 0.5.0.

I hope this all helps in some way. For the mean time, will just do it old school with a <link>.

**Comment by televators** [comment]
AHA, I think I'm on to something.
@milesingrams Are you using Dartsass? If you look at https://sass-lang.com/documentation/modules/list, at the top it says it's only supported in Dartsass, not libsass which is what node-sass uses. Anyone using node-sass-based pkgs won't be able to build from src because of this.

**Comment by mattaningram** [comment]
Yes we are using Dartsass. We are looking at removing Sass as our CSS build tool so hopefully this won't be an issue in the future. We should probably add a notice for node-sass users in the meantime.

**Comment by televators** [comment]
Ah okay. I think that would be a great idea! A notice/warning could help prevent a bunch of other issues related to this being opened and could help get more people using it since they'd have something to go on if they want to get it pulled into their builds. I finally managed to switch my Gulp setup to use Dartsass and it worked beautifully.
