### ISSUE TITLE
Animations don't run on <Suspense>

### ISSUE THREAD

**Issue by DoradoFlamingo** [ingram-projects/animxyz#68]
I know <Suspense> is experimental still but I wanted to report it here in case you knew what's up. But I'm having an issue where when I call a component that is wrapped in a <Suspense> tag, `appear` is not working with the child elements, only the root element triggered an animation. Is this known?

**Comment by milesingrams** [comment]
If I'm understanding this correctly I believe this is the intended way that Vue transitions are handled with Suspense. Since Suspense is asynchronous, the child component being swapped/loaded will be an enter animation, not an appear animation. If you can provide a codepen that would help me greatly to investigate!
